---
- name: Install sentry
  shell: "{{ virtualenv }}/bin/easy_install -UZ sentry==6.4.4 creates={{ virtualenv }}/bin/sentry"

- name: Install sentry.conf.py
  template: src=sentry.conf.py dest={{ sentry_conf_file}}
  notify:
    - reload supervisor

- name: Migrate sentry db
  shell: "{{ virtualenv }}/bin/sentry --config={{ sentry_conf_file }} upgrade --noinput"

- name: Install nginx conf
  sudo_user: root
  template: src=nginx-site.j2 dest=/etc/nginx/conf.d/sentry.conf
  notify: restart nginx

- name: Check nginx is running
  sudo_user: ubuntu
  service: name=nginx state=started

- name: Install supervisor conf
  sudo_user: root
  template: src=supervisor.j2 dest=/etc/supervisor/conf.d/sentry.conf
  notify: reload supervisor
