---
user_name: sentry
group_name: sentry
deploy_root: /opt/sentry
virtualenv: "{{ deploy_root }}/virtualenv"
conf_dir: "{{ deploy_root }}/conf"
sentry_conf_file: "{{ conf_dir }}/sentry.conf.py"
sentry_key: something
sentry_url_prefix: http://something.com  # No trailing slash!
server_email: sentry@something.com
email_host: something.com
email_host_user: somebody
email_host_password: something
